name: Cricket Playlist Bot

on:
  schedule:
    - cron: '0 */1 * * *'  # Har ghante chalega
  workflow_dispatch:       # Manual Run button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # YAHAN CHANGE KIYA HAI: requirements.txt ki jagah seedha install
      - name: Install Dependencies
        run: pip install requests pytz

      - name: Run Generator
        run: python cric_gen.py

      - name: Commit and Push
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "bot@github.com"
          git add cricket.m3u
          git commit -m "Auto Update: $(date)" || echo "No changes to commit"
          git push
