name: Cricket Bot

on:
  push:
  schedule:
    - cron: '0 */1 * * *'  # Har ghante chalega
  workflow_dispatch:       # Manual Run button

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # IMPORTANT: curl-cffi add kiya hai
      - name: Install Dependencies
        run: pip install curl-cffi pytz

      - name: Run Generator Script
        # ðŸ‘‡ Sirf ye 'env' block add kiya hai taaki secrets script tak pahunch sakein
        env:
          ONED_BASE_URL: ${{ secrets.ONED_BASE_URL }}
          ONED_SRC: ${{ secrets.ONED_SRC }}
          ONED_TARGET: ${{ secrets.ONED_TARGET }}
        run: python cric_gen.py

      - name: Commit and Push
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "bot@github.com"
          git add cricket.m3u
          git commit -m "Auto Update Playlist" || exit 0
          git push
